- hosts:
    - dbservers
  become: yes
  roles:
    # - etc-hosts
    # - postgresql  # dependencies: etc-hosts
    - pgpool-II   # dependencies: etc-hosts, postgresql
  # vars:
  # vars_files:
  #   - "inventories/{{ env }}/vars/main.yml"
  # vars_prompt:
  #   - name: is_rm_pgdata_dir
  #     prompt: "rm pgdata_dir ?"
  #     default: no
  pre_tasks:
    - tags: change_password
      name: change_password
      when: env | default("") == "vagrant"
      block:
        - user:
            name: "{{ item }}"
            password: "{{ 'a' | password_hash('sha512') }}"
          changed_when: false
          with_items:
            - vagrant
            - root
            - postgres
  # tasks:
  #   - name: test
  #     debug:
