# ##########################################################################################
# NOTE: Whether to delete the PGDATA directory or less before running PostgreSQL's initdb.
#       To delete it, add `-e is_rm_pgdata_dir = true` option at run time.
# ##########################################################################################
is_rm_pgdata_dir: false

# pg_version:       96
# pg_version_major: 9.6
# pg_version_minor: 3
pg_version:       10
pg_version_major: 10
pg_version_minor: 2 # <= minor ver num ?
rpm:
  baseurl:  "https://download.postgresql.org/pub/repos/yum/{{ pg_version_major }}/redhat/rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}/"
  filename: "pgdg-{{ ansible_distribution | lower }}{{ pg_version }}-{{ pg_version_major }}-{{ pg_version_minor }}.noarch.rpm"
  packages:
    - postgresql{{ pg_version }}.{{ ansible_architecture }}
    - postgresql{{ pg_version }}-server.{{ ansible_architecture }}
    - postgresql{{ pg_version }}-devel.{{ ansible_architecture }}
    - postgresql{{ pg_version }}-libs.{{ ansible_architecture }}
    - postgresql{{ pg_version }}-contrib.{{ ansible_architecture }}
    - python-psycopg2

postgres_home_dir: /var/lib/pgsql/
archive_dir: "{{ postgres_home_dir }}{{ pg_version_major }}/archivedir/"
backup_dir:  "{{ postgres_home_dir }}{{ pg_version_major }}/backups/"
pgdata_dir:  "{{ postgres_home_dir }}{{ pg_version_major }}/data/"

# NOTE: Since this differs for each inventory (env),
#       it moves to `./inventory/{env_name}/hosts.yml`.
# pgpass:
#   entries: []

initdb:
  pgdata:   "{{ pgdata_dir }}"
  encoding: UTF8
  locale:   C
  pwfile:   "/tmp/pwfile"
  username: "{{ superuser }}"

# NOTE: Since this differs for each inventory (env),
#       it moves to `./inventory/{env_name}/hosts.yml`.
# pg_hba_conf:
#   entries: []

postgresql_conf:
  entries:
    - listen_addresses  = '*'
    - wal_level         = replica
    - max_wal_senders   = 10 # NOTE: default 10 >= pg ver 10, default 0 < pg ver 10
    - wal_keep_segments = 32
    - archive_mode      = on
    - archive_command   = 'cp "%p" "{{ archive_dir }}%f"'
    - log_filename                = 'postgresql.log'
    - log_line_prefix             = '[%m]%u %d %p[%l]'
    - log_min_duration_statement  = 1s
    - log_checkpoints             = on
    - log_statement               = mod
    - log_replication_commands    = on
    - log_autovacuum_min_duration = 0
    # - log_connections             = on
    # - log_disconnections          = on
    # MEMO: http://www.pgpool.net/docs/latest/en/html/runtime-config-connection.html#GUC-NUM-INIT-CHILDREN
    # max_pool*num_init_children*2 <= (max_connections - superuser_reserved_connections) (query canceling needed)
    # default
    #   - max_pool                        32
    #   - num_init_children                4
    #   - max_connections                100
    #   - superuser_reserved_connections   3
    # (32 * 4 * 2) - (100 -3) = 159 shortage
    # (32 * 4 * 2) + 3(superuser_reserved_connections) = 259(max_connections)
    - max_connections = 100
    - superuser_reserved_connections = 3

create_role:
  - name:     "{{ replication_user }}"
    password: "{{ replication_password }}"
    role_attr_flags: LOGIN,REPLICATION
  - name:     "{{ pool_check_user }}"
    password: "{{ pool_check_password }}"
    role_attr_flags: LOGIN
